server:
  port: 7001

netty.server.name: server
netty.server.port: 6001

netty:
  clients:
    - name: server1
      host: localhost
      port: 6002
    - name: server1
      host: localhost
      port: 6002
  eureka:
   enable: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: server
